Diab: add proguard rules for AndroidViewModels
On "release" builds:

2018-08-27 20:12:24.109 8798-8798/it.diab E/AndroidRuntime: FATAL EXCEPTION: main
    Process: it.diab, PID: 8798
    java.lang.RuntimeException: Cannot create an instance of class it.diab.glucose.b.c
        at androidx.lifecycle.u$a.a(Unknown Source:125)
[...]
     Caused by: java.lang.NoSuchMethodException: <init> [class android.app.Application]
[...]

Signed-off-by: Joey <bevilacquajoey@gmail.com>