export: fix NoClassDefFoundError on api 25-
Inserting a date in a WorkSheet requires java 8's java.time.LocalDateTime
which does not exists in android versions prior Oreo

java.lang.NoClassDefFoundError: Failed resolution of: Ljava/time/LocalDateTime;
	at d.a.a.S.c(:1)
	at d.a.a.u.accept(lambda)
	at d.a.a.S.a(:21)
	at d.a.a.S.a(:6)
	at it.diab.glucose.export.ExportService.a(:52)
	at it.diab.glucose.export.m.b()
	at c.c.b.a.a.a(:4)
	at kotlinx.coroutines.V.run(:13)
	at kotlinx.coroutines.b.a.a(:55)
	at kotlinx.coroutines.b.a.a(:4)
	at kotlinx.coroutines.b.a$b.run(:9)

Signed-off-by: Joey <bevilacquajoey@gmail.com>