fragments: start observing onActivityCreated
On slower devices, view may be null on config change

java.lang.IllegalStateException: Can't access the Fragment View's LifecycleOwner when getView() is null i.e., before onCreateView() or after onDestroyView()

Signed-off-by: Joey <bevilacquajoey@gmail.com>